/* Generated By:JJTree: Do not edit this line. ASTArth.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTArth extends SimpleNode {
  public ASTArth(int id) {
    super(id);
  }

  public ASTArth(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5999b9882e7f3d9ad1f7b53976434a26 (do not edit this line) */
