/* Generated By:JJTree: Do not edit this line. ASTAddSub.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAddSub extends SimpleNode {
  public ASTAddSub(int id) {
    super(id);
  }

  public ASTAddSub(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebe817e76deb945b6dbc9b68894bc8db (do not edit this line) */
