/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5211be4b820d9f1aeeedba1d3fcf773a (do not edit this line) */
