/* Generated By:JJTree: Do not edit this line. ASTBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTBlock extends SimpleNode {
  public ASTBlock(int id) {
    super(id);
  }

  public ASTBlock(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=706309d73bf7b2aadcae4c660e0ff7e1 (do not edit this line) */
