/* Generated By:JJTree: Do not edit this line. ASTFactor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFactor extends SimpleNode {
  public ASTFactor(int id) {
    super(id);
  }

  public ASTFactor(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2cfec61ccd2ab4d93916bf7ec5dda024 (do not edit this line) */
