/* Generated By:JJTree: Do not edit this line. ASTFunction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFunction extends SimpleNode {
  public ASTFunction(int id) {
    super(id);
  }

  public ASTFunction(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0d092f2f0e3eac8e8e8143ffc8bfbc6 (do not edit this line) */
