/* Generated By:JJTree: Do not edit this line. ASTFunction_Call.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFunction_Call extends SimpleNode {
  public ASTFunction_Call(int id) {
    super(id);
  }

  public ASTFunction_Call(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0536135c1d25414e8ebdaf342edb2ae (do not edit this line) */
