/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f0e5a8d5a814d41741b98bd66ce0242d (do not edit this line) */
