/* Generated By:JJTree: Do not edit this line. ASTLine.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTLine extends SimpleNode {
  public ASTLine(int id) {
    super(id);
  }

  public ASTLine(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c924f2cc9e650ae3388f683c1e88c2c (do not edit this line) */
