/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21ed52ed87f46b0b2fe26c0810b18a32 (do not edit this line) */
