/* Generated By:JJTree: Do not edit this line. ASTMulDivMod.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */

public class ASTMulDivMod extends SimpleNode {
  public ASTMulDivMod(int id) {
    super(id);
  }

  public ASTMulDivMod(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void dump(String prefix) {
    if (jjtGetValue()!=null)
      System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + ((jjtGetValue()==null) ? "" : "|"));
        }
      }
    }
  }
}
/* JavaCC - OriginalChecksum=2854c89e89e697ea31ca7e458be764b3 (do not edit this line) */
