/* Generated By:JJTree: Do not edit this line. ASTParameter.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTParameter extends SimpleNode {
  public ASTParameter(int id) {
    super(id);
  }

  public ASTParameter(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7deb63af0018debf8bd20831e1a3ca3 (do not edit this line) */
