/* Generated By:JJTree: Do not edit this line. ASTParameters.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTParameters extends SimpleNode {
  public ASTParameters(int id) {
    super(id);
  }

  public ASTParameters(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=215ff89dbc1c2c0e93344344496ba55b (do not edit this line) */
