/* Generated By:JJTree: Do not edit this line. ASTSub.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTSub extends SimpleNode {
  public ASTSub(int id) {
    super(id);
  }

  public ASTSub(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c1d1c22b08c4b8ca8763d7f71a282c4 (do not edit this line) */
