/* Generated By:JJTree: Do not edit this line. ASTTest.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTTest extends SimpleNode {
  public ASTTest(int id) {
    super(id);
  }

  public ASTTest(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=959485de64e9400480fea6474fa9f41f (do not edit this line) */
