/* Generated By:JJTree: Do not edit this line. ASTTerm.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTTerm extends SimpleNode {
  public ASTTerm(int id) {
    super(id);
  }

  public ASTTerm(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d8f0f5bb3f9d4f136116d5184a1b81d8 (do not edit this line) */
