/* Generated By:JJTree: Do not edit this line. ASTValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTValue extends SimpleNode {
  public ASTValue(int id) {
    super(id);
  }

  public ASTValue(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8afaaf07c1591fa5bddbdb1a033b722b (do not edit this line) */
