/* Generated By:JJTree: Do not edit this line. ASTVar_Assignment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVar_Assignment extends SimpleNode {
  public ASTVar_Assignment(int id) {
    super(id);
  }

  public ASTVar_Assignment(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa589b4ee03dbfcac2cc73a068207c02 (do not edit this line) */
