/* Generated By:JJTree: Do not edit this line. ASTVar_Assign.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVar_Assign extends SimpleNode {
  public ASTVar_Assign(int id) {
    super(id);
  }

  public ASTVar_Assign(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5246e8e554d90f29566ded4eabe71b91 (do not edit this line) */
