/* Generated By:JJTree: Do not edit this line. ASTArithmeticExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAddSub extends SimpleNode {
  public ASTAddSub(int id) {
    super(id);
  }

  public ASTAddSub(Parser p, int id) {
    super(p, id);
  }

  @Override
  public void dump(String prefix) {
    if (jjtGetValue()!=null)
      System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + ((jjtGetValue()==null) ? "" : "|"));
        }
      }
    }
  }
}
/* JavaCC - OriginalChecksum=47517adbe244801f1d5198319a62b7c1 (do not edit this line) */
