/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFunctionCall extends SimpleNode {
  public ASTFunctionCall(int id) {
    super(id);
  }

  public ASTFunctionCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3ca40476008484c68fa12e9d5a8f40e7 (do not edit this line) */
