/* Generated By:JJTree: Do not edit this line. ASTVar_Declar.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTVar_Declar extends SimpleNode {
  public ASTVar_Declar(int id) {
    super(id);
  }

  public ASTVar_Declar(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4cbeea1c89c78a69ece40748fcf3720b (do not edit this line) */
