/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTBLOCK = 2;
  public int JJTVAR_DECLAR = 3;
  public int JJTVALUE = 4;
  public int JJTVAR_ASSIGN = 5;
  public int JJTFUNCTION_CALL = 6;
  public int JJTFUNCTIONCALL = 7;
  public int JJTADDSUB = 8;
  public int JJTMULDIVMOD = 9;
  public int JJTPARAMETERS = 10;
  public int JJTPARAMETER = 11;
  public int JJTIDENTIFIER = 12;
  public int JJTINTEGER = 13;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Block",
    "Var_Declar",
    "Value",
    "Var_Assign",
    "Function_Call",
    "FunctionCall",
    "AddSub",
    "MulDivMod",
    "Parameters",
    "Parameter",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=cfbc01ad5072d4d2465bd76079ffa168 (do not edit this line) */
